version: '2'
services:
    jenkins:
        build: .
        privileged: true
        restart: always
        ports:
            - "8090:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home/
            - /var/run/docker.sock:/var/run/docker.sock
    php:
        build: php7/
        privileged: true
        ports:
            - 22
        volumes_from:
            - jenkins
volumes:
    jenkins-data:
        driver: local
